In [ ]:
#矩阵与向量相减
#比较有意思，原矩阵是3x2的，减去np求平均后的向量，两者维度不同也可以相减
import numpy as np
data = np.arange(6).reshape((3,2))
print data
c = np.average(data, axis=0)
print c
print data - c

In [ ]:
import numpy as np

a = np.zeros((4,4,4))
b = np.zeros((4,4))
print 'a is \n',a
print 'b is \n',b

In [14]:
import numpy as np
#创建数组，数组是numpy的基石
#a中逗号隔开的为一行，即[1,2],[3,4]，方括号中为逗号隔开的为一列，即a维度是3行2列
a = np.array([[1,2],[3,4],[5,6]])
print a.shape

b = np.arange(24).reshape(2,3,4)
print b[0,...]
print b[0,:,:]
#多个冒号可以用 ... 来代替

(3, 2)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
